### ISSUE TITLE
Feat: [메인페이지] 질문하러가기 link 작업

### ISSUE THREAD

**Issue by Namgyeon** [sprint12-part2/openmind#88]
# Feat

## 어떤 기능인가요?
 - 질문하러 가기 버튼 클릭시 질문목록 페이지로 이동한다.

**Comment by cksrlcks** [comment]
요거 그냥 임시로 Link태그로 택스트로만으로도 작업해서 
pr 올려주시면 안될까욤 ㅎㅎ

오늘 1차 점검할때, 메인에서 이 버튼 리스트로 넘어가면 좋을것 같아서요
나중에 버튼 컴포넌트 작업되면, 그때 style 이라는 이슈로 만들어서 또 작업하면될거에요
(저도 다른페이지 그렇게 해뒀는데, 나중에 교체용 이슈 티켓만들어서 할라구욬ㅋ)
